# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  # Build the main binary from the cmd/ByteBucket directory
  cmd = "go build -o tmp/main ./cmd/ByteBucket"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]

[log]
  time = true