# .air.conf
root = "."
tmp_dir = "tmp"

[build]
  # Build your main package from the cmd/ByteBucket directory
  cmd = "go build -o tmp/main ./cmd/ByteBucket"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]

[log]
  time = true