name: bytebucket
services:
  bytebucket:
    build:
      context: ..          # Set context to the project root
      dockerfile: docker/Dockerfile
    ports:
      - "9000:9000"
    environment:
      - ENCRYPTION_KEY=zcY9EnJ5gVVDyfrNlXsuEOToLwC7cWsiz02xGKbBo1g=
      - ACCESS_KEY_ID=APE6at7CMFvJaEJjnmbC
      - SECRET_ACCESS_KEY=40ylGQ3lRaxE/SQFRZrHZY+e+XD7CBMVa8ioUsAO
    volumes:
      - ../data:/data